SELECT 
MAX(IF(OCCUPATION="Doctor", NAME, Null)) AS Doctor,
MAX(IF(OCCUPATION="Professor", NAME, Null)) AS Professor,
MAX(IF(OCCUPATION="Singer", NAME, Null)) AS Singer,
MAX(IF(OCCUPATION="Actor", NAME, Null)) AS Actor
FROM
(SELECT NAME, OCCUPATION, ROW_NUMBER() OVER(PARTITION BY OCCUPATION ORDER BY NAME )
AS ROW_NO FROM OCCUPATIONS) as occupation_rows GROUP By ROW_NO;